### ISSUE TITLE
[BUG] 2EXT03_Metabolites.xlsx

### ISSUE THREAD

**Issue by SilkeGerlich** [nfdi4plants/SWATE_templates#11]
Concerning [the Metabolites template](https://github.com/nfdi4plants/SWATE_templates/blob/main/templates/2EXT03_Metabolites/2EXT03_Metabolites.xlsx)

The third term is **Protocol REF Extraction**, with no description added. 

Could anyone give more detail on this term? Could it be an artifact?

**Comment by omaus** [comment]
As far as I remember, it had sth. to do with the Metabolights ER. They would need to have different parts of their submission separated by such columns. In this case, `Protocol REF Extraction` would open a series of columns that are linked to their extraction protocol term-group and this series ends with the next `Protocol REF` column.
I think @Brilator might elaborate further on this.

**Comment by Martin-Kuhl** [comment]
Oliver is right. The note from MetaboLights to this is:

"This is the column marking the start of data pertaining to Extraction. The example term MUST be present in all rows of this column."

There are also more columns of this type, such as Protocol REF - Chromatography or Protocol REF - Mass spectrometry, which just have not been added yet (also in other templates for the said ER). The templates will receive a needed update in the near future.
