### ISSUE TITLE
[BUG] Buffer and Extraction Buffer

### ISSUE THREAD

**Issue by HajiraJabeen** [nfdi4plants/SWATE_templates#13]
**Describe the bug**
In extraction templates RNA, DNA, Metabolites we use a [Extraction buffer]->NFDI4PSO:0000050.
Whereas,  **02EXT02_protein** uses [Buffer]->CHEBI:35225.
"

**To Reproduce**
In the "EXT" templates at https://github.com/nfdi4plants/SWATE_templates/tree/main/templates

**Expected behavior**
The parameter _Extraction buffer]->NFDI4PSO:0000050_ in other templates be **renamed** to [Buffer]->CHEBI:35225 for consistency.

**Additional context**

**Comment by omaus** [comment]
Same as #12 : `Buffer` is a term from the CHEBI ontology that rather should be cross-ref'd by our NFDI4PSO term `Extraction buffer`, imho.
I'd rather like to exchange the CHEBI term with ours.

**Comment by omaus** [comment]
Clarification: As discussed in https://github.com/orgs/nfdi4plants/teams/data-stewards/discussions/40 , CHEBI's `buffer` should be parent term for our broker ontology's `Extraction buffer` term since there are different kinds of buffers.

**Comment by Brilator** [comment]
Closing this issue, since it's an ontology-related issue and relates to mostly deprecated or since then changed concepts / use of the ontology
