### ISSUE TITLE
[BUG] remove scripts 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/SWATE_templates#25]
Are the conversion (?) scripts still relevant? 
I assume we can safely archive them somewhere else to reduce confusions. 

https://github.com/nfdi4plants/SWATE_templates/tree/main/Scripts

**Comment by omaus** [comment]
https://github.com/nfdi4plants/SWATE_templates/commit/74632dcfc2f66d643294c4b3f7dfc46173f6bdc3
