### ISSUE TITLE
[BUG] CustomXml is not managed correctly.

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/SWATE_templates#4]
**Describe the bug**
Example: In the .json is written: `"Worksheet" : "1SPL02_ProteomicsSamplePreparation"` and the xml contains not a single Swate tag with that worksheetname (exmp: `<SwateTable Table="annotationTable1" Worksheet="Measurement">`).

I can show you tomorrow how to manage custom xml with the new features in Swate.

**Comment by Brilator** [comment]
Done for the GEO examples. @Freymaurer, please double-check

**Comment by Freymaurer** [comment]
This is in reference to #3. `4COM01_RNASeqGEO` still contains no custom xml.
We want to put emphasis to this checklist provided by the templates. This was a huge deal for Timo, so please add some checklist to it. In addition, both the webhook and Swate are currently not able to correctly handle template without customXml.

**Comment by Freymaurer** [comment]
I will add minimal checklist xml for now.
